### ISSUE TITLE
bamboo-pipeline 3.24.5/3.24.6 更新的 celery 5.x 版本 与 python 版本限制冲突问题

### ISSUE THREAD

**Issue by AloneFire** [TencentBlueKing/bamboo-engine#229]
3.24.5/3.24.6 更新的 celery 版本，依赖的最小 python 版本为 3.8
这与 3.24分支中限制 `python = ">= 3.6, < 3.8" ` 有冲突
顺便说一下 是不是可以 同时放开 django 版本的限制

**Comment by normal-wls** [comment]
celery 5.1.2 是适配 py 3.6-3.7，我们已经在主分支放开了 celery 、python 和 django 的限制，可以体验下3.29.3版本
